# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
- group: back_end_url_details


steps:

- task: replacetokens@6
  displayName: replace
  inputs:
    root: '$(System.DefaultWorkingDirectory)'
    sources: '**/api.js'
- task: Npm@1
  displayName: npm 
  inputs:
    command: 'install'
- task: Npm@1
  displayName: build
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: PublishBuildArtifacts@1
  displayName: publish
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
    publishLocation: 'Container'